-- MySQL Script generated by MySQL Workbench
-- 03/07/17 14:08:23
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema uemg_eventos
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema uemg_eventos
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `uemg_eventos` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `uemg_eventos` ;

-- -----------------------------------------------------
-- Table `uemg_eventos`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `uemg_eventos`.`categoria` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `uemg_eventos`.`cursos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `uemg_eventos`.`cursos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `uemg_eventos`.`eventos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `uemg_eventos`.`eventos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(45) NOT NULL,
  `descricao` LONGTEXT NOT NULL,
  `data_inicio` DATE NOT NULL,
  `data_fim` DATE NOT NULL,
  `organizador` VARCHAR(45) NOT NULL,
  `valor` FLOAT NULL,
  `pagar_para` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `uemg_eventos`.`atividades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `uemg_eventos`.`atividades` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(45) NOT NULL,
  `descricao` LONGTEXT NOT NULL,
  `vagas_total` INT NULL,
  `vagas_disp` INT NULL,
  `ministrante` VARCHAR(45) NOT NULL,
  `data_inicio` DATETIME NOT NULL,
  `data_fim` DATETIME NOT NULL,
  `local` VARCHAR(45) NOT NULL,
  `id_categoria` INT NOT NULL,
  `id_curso` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_atividades_categoria_idx` (`id_categoria` ASC),
  INDEX `fk_atividades_cursos1_idx` (`id_curso` ASC),
  CONSTRAINT `fk_atividades_categoria`
    FOREIGN KEY (`id_categoria`)
    REFERENCES `mydb`.`categoria` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_atividades_cursos1`
    FOREIGN KEY (`id_curso`)
    REFERENCES `mydb`.`cursos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `uemg_eventos`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `uemg_eventos`.`usuarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `ra` VARCHAR(45) NULL,
  `turma` VARCHAR(45) NULL,
  `cpf` VARCHAR(45) NULL,
  `admin` TINYINT(1) NULL,
  `id_curso` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_usuarios_cursos1_idx` (`id_curso` ASC),
  CONSTRAINT `fk_usuarios_cursos1`
    FOREIGN KEY (`id_curso`)
    REFERENCES `mydb`.`cursos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
